name: Steam GetAppInfo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
      
      - name: Install dependencies
        run: |
          uv pip install --no-cache-dir -r requirements.txt
          
      - name: Run crontab.py
        run: |
          python crontab.py
      
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'main'
          commit_message: 'Update AppInfo'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
